from typing import Optional
from pydantic import Field
from hyko_sdk import CoreModel, extract_metadata

description = "OpenAI's GPT 3.5 Turbo Summarization model (API)"

class Inputs(CoreModel):
    text: str = Field(..., description="Input text (4k tokens max context size)")

class Params(CoreModel):
    api_key: str = Field(..., description="OpenAI's API KEY")
    max_tokens: Optional[int] = Field(default=None, description="Maximum number of tokens generated by the model")
    temperature: Optional[float] = Field(default=None, description="Model's temperature")
    top_p: Optional[float] = Field(default=None, description="Model's Top P")

class Outputs(CoreModel):
    summary: str = Field(..., description="Summarized text")

if __name__ == "__main__":
    extract_metadata(
                    Inputs, Params, Outputs,  # type: ignore
                    description, False
                )