from typing import Optional
from pydantic import Field
from hyko_sdk import CoreModel, extract_metadata

description = "OpenAI's GPT 3.5 Turbo Large completion model (API)"

class Inputs(CoreModel):
    prompt: str = Field(..., description="Input prompt (16k tokens max context size)")

class Params(CoreModel):
    system_prompt: Optional[str] = Field(default=None, description='System prompt for the model (used to instruct the model)')
    api_key: str = Field(..., description="OpenAI's API KEY")
    max_tokens: Optional[int] = Field(default=None, description="Maximum number of tokens generated by the model")
    temperature: Optional[float] = Field(default=None, description="Model's temperature")
    top_p: Optional[float] = Field(default=None, description="Model's Top P")

class Outputs(CoreModel):
    completion_text: str = Field(..., description="Completion text")

if __name__ == "__main__":
    extract_metadata(
                    Inputs, Params, Outputs,  # type: ignore
                    description, False
                )