FROM hyko-sdk:latest AS main

WORKDIR /app

RUN pip install openai

COPY main.py .
COPY config.py .

CMD ["uvicorn", "--host", "0.0.0.0", "--port", "3000", "main:app"]

FROM main AS metadata

CMD ["python", "-m", "config"]