import openai
from pydantic import Field
from hyko_sdk import CoreModel, SDKFunction
from typing import Optional


func = SDKFunction(
    description="OpenAI's GPT 4 Large Summarization model (API)",
    requires_gpu=False,
)

class Inputs(CoreModel):
    text: str = Field(..., description="Input text (32k tokens max context size)")

class Params(CoreModel):
    api_key: str = Field(..., description="OpenAI's API KEY")
    max_tokens: Optional[int] = Field(default=None, description="Maximum number of tokens generated by the model")
    temperature: Optional[float] = Field(default=None, description="Model's temperature")
    top_p: Optional[float] = Field(default=None, description="Model's Top P")

class Outputs(CoreModel):
    summary: str = Field(..., description="Summarized text")


@func.on_execute
async def main(inputs: Inputs, params: Params):

    chat_completion = await openai.ChatCompletion.acreate(
        model="gpt-4-32k",
        messages=[
            {
                "role": "system",
                "content": "Summarize this",
            },
            {
                "role": "user",
                "content": inputs.text,
            },
        ],
        api_key=params.api_key,
        max_tokens=params.max_tokens,
        temperature=params.temperature,
        top_p=params.top_p,
    )

    completion: str = chat_completion.choices[0].message.content # type: ignore

    return Outputs(summary=completion)

